// <auto-generated />
using System;
using GomezcoelloCristian_PruebaProgreso1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GomezcoelloCristian_PruebaProgreso1.Migrations
{
    [DbContext(typeof(GomezcoelloCristian_PruebaProgreso1Context))]
    [Migration("20241029124116_MigarcionInicial")]
    partial class MigarcionInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GomezcoelloCristian_PruebaProgreso1.Models.Celular", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Precio")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Celular");
                });

            modelBuilder.Entity("GomezcoelloCristian_PruebaProgreso1.Models.Gomezcoello", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("DireccionDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("Edad")
                        .HasColumnType("float");

                    b.Property<int>("Hermanos")
                        .HasColumnType("int");

                    b.Property<int>("IdCelular")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Quiteno")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("IdCelular");

                    b.ToTable("Gomezcoello");
                });

            modelBuilder.Entity("GomezcoelloCristian_PruebaProgreso1.Models.Gomezcoello", b =>
                {
                    b.HasOne("GomezcoelloCristian_PruebaProgreso1.Models.Celular", "Celular")
                        .WithMany()
                        .HasForeignKey("IdCelular")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Celular");
                });
#pragma warning restore 612, 618
        }
    }
}
